import CTA from "./components/CTA";
import Contact from "./components/Contact";
import Features from "./components/Features";
import Footer from "./components/Footer";
import Gallery from "./components/Gallery";
import Hero from "./components/Hero";
import News from "./components/News";
import Players from "./components/Players";
import Whyus from "./components/Whyus";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <div
      id="sections"
      className="flex flex-col w-screen xl:w-[85%] xl:ml-auto xl:max-h-full"
    >
      <div className="xl:min-h-[calc(100vh-60px)] lg:max-h-[calc(100vh-60px)] relative">
        <Hero />
      </div>
      <div id="news" className="xl:min-h-max">
        <News />
      </div>
      <div className="xl:min-h-max ">
        <Whyus />
      </div>
      <div className="xl:min-h-max ">
        <Features />
      </div>
      <div id="team" className="xl:min-h-max ">
        <Players />
      </div>
      <div id="gallery" className="xl:min-h-max ">
        <Gallery />
      </div>
      <div className="xl:min-h-max ">
        <CTA />
      </div>
      <div id="contact" className="xl:min-h-max ">
        <Contact />
      </div>
      <div className="xl:min-h-max">
        <Footer />
      </div>
    </div>
  );
};

export default Home;
