import CTA from "./components/CTA";
import Contact from "./components/Contact";
import Features from "./components/Features";
import Footer from "./components/Footer";
import Hero from "./components/Hero";
import News from "./components/News";
import Players from "./components/Players";
import Whyus from "./components/Whyus";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Home = () => {
  return (
    <div id="sections" className="flex flex-col w-[85%] ml-auto max-h-full">
      <div className="min-h-[calc(100vh-60px)] max-h-[calc(100vh-60px)] relative">
        <Hero />
      </div>
      <div className="min-h-max">
        <News />
      </div>
      <div className="min-h-max ">
        <Whyus />
      </div>
      <div className="min-h-max ">
        <Features />
      </div>
      <div className="min-h-max ">
        <Players />
      </div>
      <div className="min-h-max ">
        <CTA />
      </div>
      <div className="min-h-max ">
        <Contact />
      </div>
      <div className="min-h-max">
        <Footer />
      </div>
    </div>
  );
};

export default Home;
